
jiveBelarus = ['CAACAgIAAxkBAAIBv1_jqRpUC2LgrZyz1gTEjhFtDsW2AAL7AANSiZEjHEzYB3L4zKweBA',
               'CAACAgIAAxkBAAIBwF_jqRyun8yzidGWkUNcxRHFRybXAALyAANSiZEjcVvbeESmH1EeBA',
               'CAACAgIAAxkBAAIBwV_jqR3RdupkB6QNMK9f_EBy1cdOAALzAANSiZEjToACKbnf1XUeBA',
               'CAACAgIAAxkBAAIBwl_jqR-tjIqiJjtGU8Z1E3W-DFuyAAL0AANSiZEjkWNnOQwHwt4eBA',
               'CAACAgIAAxkBAAIBw1_jqSHyJ2L4ZRRvMDJexfhCqdq9AAL3AANSiZEjonpibT_h-0ceBA',
               'CAACAgIAAxkBAAIBxF_jqSJdILeOtZCKEZyBYA87bD4JAAL5AANSiZEjf7_e7W0V90MeBA',
               'CAACAgIAAxkBAAIBxl_jqScvu0kIe9k0Iz4c_GjdwjcRAAJeAgACVp29Cv4tArVWoecTHgQ',
               'CAACAgIAAxkBAAIBx1_jqSjt0dNUoM05KHARtxcw2V-rAAJhAgACVp29CrR03tZ0GvlWHgQ',
               'CAACAgIAAxkBAAIByF_jqTSKXfQ4dHhD0CX3u1IXnqcmAAJcAwACierlB9XqFLr4k5wgHgQ',
               'CAACAgIAAxkBAAIBxV_jqSOG55xV4VibUrQAARRCBTH2yAACIwEAAlKJkSM1jXxxn9X20x4E']